name: lonewolf_new
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_redux_dev_tools: ^0.5.2
  http: ^0.13.5
  intl: ^0.17.0
  recase: ^4.0.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  shared_preferences: ^2.0.15
  slang: ^2.7.0
  slang_flutter: ^2.7.0
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  test: ^1.21.1

flutter:
  uses-material-design: true
