name: aonic
description: Play Lone Wolf games books from Project Aon on desktop/mobile device. Built with Flutter.

publish_to: 'none'

version: 0.2.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_redux: ^0.10.0
  flutter_redux_dev_tools: ^0.5.2
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  recase: ^4.0.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  shared_preferences: ^2.0.15
  slang: ^2.7.0
  slang_flutter: ^2.7.0
  url_launcher: ^6.1.7
  xml: ^6.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0
  test: ^1.21.1

flutter:
  assets:
    - samples/sample.xml
  
  uses-material-design: true

